
oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: OCPlatformBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

