# src/OC/PlatformBundle/Resources/config/services.yml
parameters:
    mon_parametre: 'param value just to test'
    m_web_dir: '__DIR__./../../../../../web/uploads/img/'

services:
    oc_platform.antispam:
        class:     OC\PlatformBundle\Antispam\OCAntispam
        arguments: ["@mailer", "%locale%", "5"]
        tags:
            -  { name: twig.extension }

    oc_platform.doctrine.notification:
        class: OC\PlatformBundle\DoctrineListener\ApplicationNotification
        arguments: ["@mailer", "@session"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    oc_platform.beta.html:
        class: OC\PlatformBundle\Beta\BetaHTML

    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments: ["@oc_platform.beta.html", "2016-06-30"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }

    oc_platform.handler.advert:
        class: OC\PlatformBundle\Handler\AdvertHandler
        arguments: ["@doctrine.orm.entity_manager"]


